environment: ../../.env  # Path to the .env file for global environment variable resolution

database:
  DB_RESET: "false"  # Deletes and recreates the database (dangerous)
  REMIGRATE: "false"  # Remigrates the database
  DJANGO_DB_HOST: "db"
  DJANGO_DB_PORT: "${DB_PORT}"
  DJANGO_DB_USER: "${DB_USER}"
  DJANGO_DB_PASSWORD: "${DB_PASSWORD}"

webconfig:
  SERVICE_NAME: "donknabberello"
  DJANGO_WEB_PORT: "${PROJECT_PORT}"
  DJANGO_WEB_HOST: "${PROJECT_HOST}"

admin:
  ADMIN_USER: "admin"
  ADMIN_PASSWORD: "admin"
  ADMIN_EMAIL: "admin@admin.com"

terminal:
  TERMINAL_SERVICES: "http://terminal1:${PROJECT_PORT}/terminal1"
