ENV: "../../.env"  # Path to the .env file for global environment variable resolution

database:
  RESET: False  # Deletes and recreates the database (dangerous)
  REMIGRATE: False  # Remigrates the database
  
  HOST: "${ENV.PROJECT_HOST}"                       # Database server (docker image name)
  PORT: "${ENV.DB_PORT}"               # Database port
  USER: "${ENV.DB_USER}"
  PASSWORD: "${ENV.DB_PASSWORD}"
  NAME: "transactify_${webservice.SERVICE_NAME}"
  
webservice:
  SERVICE_NAME: <SERVICE_NAME>            # Enter the service name here, this is also the subdomain, e.g. https://<IP>:<PORT>/<SERVICE_NAME>
  FRIENDLY_NAME: <FRIENDLY_NAME>          # Friendly name of the service (will be displayed in the frontend and the Terminal)
  SERVICE_WEB_HOST: "${ENV.PROJECT_HOST}"
  SERVICE_WEB_PORT: ${ENV.PROJECT_PORT}
  JOURNAL_FILE: "journal_${SERVICE_NAME}.py"
  
admin:
  ADMIN_USER: "admin"
  ADMIN_PASSWORD: "admin"
  ADMIN_EMAIL: "admin@admin.com"

terminal:
  TERMINAL_SERVICE: terminal1
  TERMINAL_SERVICE_URL: "${TERMINAL_SERVICE}:${ENV.PROJECT_PORT}/${TERMINAL_SERVICE}"
  TERMINAL_WEBSOCKET_URL: "${TERMINAL_SERVICE_URL}/ws"
  TERMINAL_SELECTION_BUTTONS: A

# Other configurations
django:
  DEBUG: False
  SECRET_KEY: "YourSecretKey"
  # The path to the static files
  STATIC_URL: "static/"
  STATIC_ASSETS_PATH: "assets_hyper/"
  # If those are set, the static path points to a different location instead of localhost
  STATIC_WEBSERVER: "http://${ENV.PROJECT_HOST}:${ENV.PROJECT_PORT}"