version: '3.9'

services:
  

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:${DB_PORT}
  
  terminal1:
    build:
      context: .
      dockerfile: ./transactify_terminal/Dockerfile
    restart: always
    privileged: true  # Grants access to devices and kernel features
    cap_add:
      - SYS_RAWIO  # Allows raw GPIO access
    security_opt:
      - apparmor:unconfined  # Unrestricted access to hardware
    volumes:
      - /run/docker.sock:/run/docker.sock:ro
      - nginx_data:/etc/nginx/conf.d
      - static_volume:/app/static
    environment:
      - TERMINAL_CONFIG_FILE=/app/configs/terminal_config.yaml
    depends_on:
    #   - doncaramello
      - donknabberello 
    healthcheck:
      test: "curl http://127.0.0.1:${PROJECT_PORT}/terminal1/health"
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 10
    deploy:       # limit maximum number of containers to 1
      replicas: 1 # Important for the terminal to work properly (only one terminal can be connected to the hardware)
  
  donknabberello:
    build:
      context: .
      dockerfile: ./transactify_service/Dockerfile
    restart: always
    depends_on:
      - db
    volumes:
      # Configuration file for the store
      - .env:/app/.env
      - ./transactify_service/configs/store_config.yaml:/app/configs/store_config.yaml
      # Docker socket for container management
      - /run/docker.sock:/run/docker.sock:ro
      # Data: Nginx configuration and static files
      - nginx_data:/etc/nginx/conf.d
      - static_volume:/app/static
    healthcheck:
      test: "curl http://127.0.0.1:${PROJECT_PORT}/donknabberello/health"
      start_period: 10s
      interval: 10s
      timeout: 10s
      retries: 10


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    #depends_on:
    #  - django

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      #- static_volume:/static
      - ./static:/static
      - ./common/nginx/nginx.conf:/etc/nginx/nginx.conf
      - nginx_data:/etc/nginx/conf.d
      
      - /proc/sysrq-trigger:/sysrq
      # - ./nginx/nginx.sh:/docker-entrypoint.d/nginx.sh
      #- ./nginx/nginx.donknabberello.conf:/etc/nginx/nginx.donknabberello.conf
    ports:
      - 8000:8000
    #depends_on:
    #  donknabberello:
    #    condition: service_started
    #  doncaramello:
    #    condition: service_started
    #  terminal1:
    #    condition: service_healthy
    # COmmand to remove all nginx.*.conf files bevor starting the container using the default entrypoint
    #entrypoint: [
    #  "/bin/bash",
    #  "-c",
    #  "rm -f /etc/nginx/conf.d/nginx.*.conf && /docker-entrypoint.sh;"
    #]
    
    
    



volumes:
  nginx_data:
  postgres_data:
  static_volume: