version: '3.9'

services:
  

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: USER
      POSTGRES_PASSWORD: PASSWORD
    ports:
      - 5432:5432
  
  terminal1:
    build:
      context: .
      dockerfile: ./transactify_terminal/Dockerfile
    restart: always
    privileged: true  # Grants access to devices and kernel features
    cap_add:
      - SYS_RAWIO  # Allows raw GPIO access
    security_opt:
      - apparmor:unconfined  # Unrestricted access to hardware
    environment:
      REMIGRATE: "false"
      SERVICE_NAME: "terminal1"
      SERVICE_HOST: ${PROJECT_HOST} # use  from .env
      PORT: ${PROJECT_PORT}
      # 
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_USER: USER
      DJANGO_DB_PASSWORD: PASSWORD
     
      #TARGET_SERVICES: http://192.168.1.190:8000/donknabberello #, http://service2:8000
    depends_on:
      - doncaramello
      - donknabberello 
  
  donknabberello:
    build:
      context: .
      dockerfile: ./transactify_service/Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      REMIGRATE: "false" # Only set this to true if you want to remigrate the database (also deletes all data)
      SERVICE_NAME: "donknabberello"
      # Database Setting
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_USER: USER
      DJANGO_DB_PASSWORD: PASSWORD
      # Django Setting
      DJANGO_WEB_PORT: ${PROJECT_PORT}
      DJANGO_WEB_HOST: ${PROJECT_HOST}
      #
      TERMINAL_SERVICES: http://terminal1:${PROJECT_PORT}/terminal1
    volumes:
      - static_volume:/app/staticfiles
    

  doncaramello:
    build:
      context: .
      dockerfile: ./transactify_service/Dockerfile
    restart: always
    depends_on:
      - db
    environment:
      REMIGRATE: "false"
      SERVICE_NAME: "doncaramello"
      # Database Setting
      DJANGO_DB_HOST: db
      DJANGO_DB_PORT: 5432
      DJANGO_DB_USER: USER
      DJANGO_DB_PASSWORD: PASSWORD
      # Django Setting
      DJANGO_WEB_PORT: ${PROJECT_PORT}
      DJANGO_WEB_HOST: ${PROJECT_HOST}
      #
      TERMINAL_SERVICES: http://terminal1:${PROJECT_PORT}/terminal1
    volumes:
      - static_volume:/app/staticfiles


  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    #depends_on:
    #  - django

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - static_volume:/static
      #- ./static:/static
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.donknabberello.conf:/etc/nginx/nginx.donknabberello.conf
    ports:
      - 8000:8000
    depends_on:
      - donknabberello
      - doncaramello
      - terminal1



volumes:
  postgres_data:
  static_volume: