# Generated by Django 4.2.16 on 2024-11-16 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productresellprice',
            name='ean',
        ),
        migrations.AddField(
            model_name='productresellprice',
            name='product_info',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='store.productinfo'),
            preserve_default=False,
        ),
    ]
