# Generated by Django 5.1.3 on 2024-11-26 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='id',
        ),
        migrations.RemoveField(
            model_name='storeproduct',
            name='store',
        ),
        migrations.AlterField(
            model_name='storeproduct',
            name='ean',
            field=models.CharField(primary_key=True, serialize=False, unique=True),
        ),
    ]
