# Generated by Django 5.1.3 on 2024-11-29 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_storelog_customerbalance_total_deposits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
