# Generated by Django 4.2.16 on 2024-11-16 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_productresellprice_ean_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='resell_price',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='store.productresellprice'),
            preserve_default=False,
        ),
    ]
