# Generated by Django 4.2.16 on 2024-11-16 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_resell_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='resell_price',
        ),
        migrations.AddField(
            model_name='productinfo',
            name='resell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ProductResellPrice',
        ),
    ]
