# Generated by Django 4.2.16 on 2024-11-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_product_resell_price_productinfo_resell_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinfo',
            name='resell_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
