# Generated by Django 4.2.16 on 2024-11-16 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_stockproductpurchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockproductpurchase',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product'),
        ),
    ]
