from decimal import Decimal
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework import status

from store.webmodels.Customer import Customer
from store.helpers.ManageStockHelper import StoreHelper
import json

class CustomerPurchaseAPIView(APIView):
    def post(self, request, *args, **kwargs):
        """
        Handle a customer purchase request.
        """
        try:
            # Parse and validate JSON data from the request body.
            data = json.loads(request.body)
            ean = data.get('ean')
            quantity = data.get('quantity')
            card_number = data.get('card_number')
        except json.JSONDecodeError as e:
            # Change No. #1: Added specific error handling for JSON decoding errors.
            return Response(
                {"error": f"Invalid JSON format: {str(e)}"},
                status=status.HTTP_400_BAD_REQUEST,
            )
        except Exception as e:
            # General error for request body parsing.
            return Response(
                {"error": f"Error parsing request data: {str(e)}"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        # Validate required fields
        if not all([ean, quantity, card_number]):
            # Change No. #2: Corrected the error message to reflect actual required fields.
            return Response(
                {"error": "All fields (ean, quantity, card_number) are required."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            quantity = int(quantity)
            if quantity <= 0:
                # Change No. #3: Ensure quantity is a positive integer.
                return Response(
                    {"error": "Quantity must be a positive integer."},
                    status=status.HTTP_400_BAD_REQUEST,
                )
        except ValueError:
            # Handle invalid integer conversion for quantity.
            return Response(
                {"error": f"Invalid data for quantity. Must be an integer but was '{quantity}'"},
                status=status.HTTP_400_BAD_REQUEST,
            )

        try:
            # Assuming ManageStockHelper handles the logic for the purchase
            response, customer = StoreHelper.customer_purchase(
                ean, quantity, card_number
            )
        except Exception as e:
            # Change No. #4: Handle unexpected exceptions from ManageStockHelper.
            return Response(
                {"error": f"An error occurred during the purchase: {str(e)}"},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        if response is None:
            # Change No. #5: Ensure a response is always returned by ManageStockHelper.
            return Response(
                {"error": "Unexpected error: No response from ManageStockHelper."},
                status=status.HTTP_500_INTERNAL_SERVER_ERROR,
            )

        # Return the response generated by ManageStockHelper.
        return response
