"""
Django settings for transactify_service project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import sys

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-804j38-egddb2k2+jt!52)%*k89ohsg$i0@*&oxbp@0z2r_i^!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

STORE_NAME = os.getenv('SERVICE_NAME', 'store')

ALLOWED_HOSTS = [
    STORE_NAME,
    os.getenv('DJANGO_WEB_HOST', '*'),
    'localhost',
] 


# Application definition

INSTALLED_APPS = [
    'channels',
    'daphne',
    'rest_framework',
    #
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    #
    'transactify_service',
    'store',
    'api'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CSRF_TRUSTED_ORIGINS = [
    "http://127.0.0.1",
    "http://localhost",
    "http://127.0.0.1:8000",
    "http://localhost:8000",
    f"http://{os.getenv('DJANGO_WEB_HOST', 'localhost')}",
    f"http://{os.getenv('DJANGO_WEB_HOST', 'localhost')}:{os.getenv('DJANGO_WEB_PORT', '8000')}",
    f"https://{os.getenv('DJANGO_WEB_HOST', 'localhost')}",
    f"https://{os.getenv('DJANGO_WEB_HOST', 'localhost')}:{os.getenv('DJANGO_WEB_PORT', '8000')}",
]
CSRF_FAILURE_VIEW = "transactify_service.views.custom_csrf_failure_view"


ROOT_URLCONF = 'transactify_service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'transactify_service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': STORE_NAME,
        'USER': os.getenv('DJANGO_DB_USER', 'default_user'),
        'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', 'default_password'),
        'HOST': os.getenv('DJANGO_DB_HOST', 'localhost'),
        'PORT': os.getenv('DJANGO_DB_PORT', '5432'),
    },
    # 'USER': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'USER',
    #     'USER': os.getenv('DJANGO_DB_USER', 'default_user'),
    #     'PASSWORD': os.getenv('DJANGO_DB_PASSWORD', 'default_password'),
    #     'HOST': os.getenv('DJANGO_DB_HOST', 'localhost'),
    #     'PORT': os.getenv('DJANGO_DB_PORT', '5432'),
    # },
}
# Use in-memory SQLite for testing
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'test_db',
        'USER': 'USER',
        'PASSWORD': 'PASSWORD',
        'HOST':'192.168.1.190',
        'PORT': 5432,
    }
# Important, to make the correct database routing work
#DATABASE_ROUTERS = ['transactify_service.db_router.MultiDatabaseRouter']


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'store_logs_db': {
            'level': 'DEBUG',
            'class': 'store.StoreLogsDBHandler.StoreLogsDBHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
    
}

REST_FRAMEWORK = {
    # Custom exception handler to always return a JSON response
    'EXCEPTION_HANDLER': 'transactify_service.APIResponse.custom_exception_handler',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'api.authentication.APIKeyAuthentication',
        'rest_framework.authentication.SessionAuthentication',  # Optional: Keep session auth for logged-in users
    ],
}

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'store_logs_db': {
            'level': 'DEBUG',
            'class': 'store.StoreLogsDBHandler.StoreLogsDBHandler',
        },
        'console': {
            'level': 'DEBUG',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
    
}