# Generated by Django 5.1.4 on 2025-01-15 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=36, unique=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('service_name', models.CharField(blank=True, max_length=255, null=True)),
                ('web_address', models.URLField(blank=True, null=True)),
                ('docker_container', models.CharField(blank=True, max_length=255, null=True)),
                ('terminal_button', models.CharField(blank=True, max_length=5, null=True)),
                ('incoming_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('incoming_port', models.PositiveIntegerField(blank=True, null=True)),
                ('is_connected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='StoreLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loglevel', models.CharField(max_length=50)),
                ('module', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
