# Generated by Django 5.1.4 on 2025-01-15 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0003_remove_store_incoming_ip_remove_store_incoming_port_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeconnection',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='terminal.store'),
        ),
    ]
