# Generated by Django 5.1.4 on 2025-01-19 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0004_alter_storeconnection_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelog',
            name='traceback',
            field=models.TextField(null=True),
        ),
    ]
