# Generated by Django 5.1.4 on 2025-01-19 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0005_storelog_traceback'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTraceback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traceback', models.TextField()),
                ('line_no', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='storelog',
            name='traceback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='terminal.logtraceback'),
        ),
    ]
