# Generated by Django 5.1.4 on 2025-01-20 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('terminal', '0006_logtraceback_alter_storelog_traceback'),
    ]

    operations = [
        migrations.AddField(
            model_name='storelog',
            name='source_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storelog',
            name='source_line',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
