# Generated by Django 5.1.3 on 2024-11-26 12:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')  # Import the Group model
    roles = ['Admin', 'Owner', 'Manager', 'Customer', 'None']
    for role in roles:
        Group.objects.get_or_create(name=role)

class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('card_number', models.CharField(primary_key=True, serialize=False)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RunPython(create_groups),
    ]
