# Generated by Django 5.1.3 on 2024-12-07 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashlessui', '0002_remove_customer_balance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customer',
            table='customer',
        ),
    ]
