# Generated by Django 5.1.4 on 2025-01-31 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerconfig',
            name='customer_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productrestock',
            name='undo_allowed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customerconfig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
