# Generated by Django 5.1.4 on 2025-01-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeproduct',
            name='final_price',
        ),
    ]
