# Generated by Django 5.1.4 on 2025-01-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storecashwithdraw',
            name='product_restock',
        ),
        migrations.AddField(
            model_name='productrestock',
            name='cash_movement_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='productrestock',
            name='cash_movement_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
