# Generated by Django 5.1.4 on 2025-01-23 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='image_url',
            field=models.URLField(max_length=255, null=True),
        ),
    ]
