# Generated by Django 5.1.4 on 2025-01-17 19:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_storecashwithdraw_product_restock_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreCashDeposit',
            new_name='StoreCashMovement',
        ),
        migrations.RemoveField(
            model_name='storecashwithdraw',
            name='user',
        ),
        migrations.RemoveField(
            model_name='productrestock',
            name='cash_movement_id',
        ),
        migrations.DeleteModel(
            name='StoreCashCashout',
        ),
        migrations.DeleteModel(
            name='StoreCashWithdraw',
        ),
    ]
