# Generated by Django 5.1.3 on 2025-01-09 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customerpurchase_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='total_orders',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='total_revenue',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
