# Generated by Django 5.1.4 on 2025-02-12 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_customerconfig_customer_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerconfig',
            name='email_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='customerconfig',
            name='email_on_balance_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerconfig',
            name='email_on_deleted',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerconfig',
            name='email_on_deposit',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerconfig',
            name='email_on_disabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerconfig',
            name='email_on_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerconfig',
            name='email_on_low_balance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerconfig',
            name='email_on_purchase',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='customerconfig',
            name='email_on_purchase_change',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='customerconfig',
            name='auto_deposit',
            field=models.BooleanField(default=True),
        ),
    ]
