# Generated by Django 5.1.3 on 2025-01-06 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storeproduct_final_price_alter_storeproduct_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='product_calories',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='storeproduct',
            name='product_fill_amout',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
