# Generated by Django 5.1.3 on 2025-01-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_storeproduct_total_orders_storeproduct_total_revenue'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpurchase',
            name='order_status',
            field=models.CharField(default='pending', max_length=100),
        ),
        migrations.AddField(
            model_name='customerpurchase',
            name='payment_status',
            field=models.CharField(default='pending', max_length=100),
        ),
    ]
