# Generated by Django 5.1.4 on 2025-01-17 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_storecashdeposit_storecashmovement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productrestock',
            name='cash_movement_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.storecashmovement'),
        ),
    ]
