# Generated by Django 5.1.4 on 2025-03-04 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_customerconfig_email_enabled_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='card_number',
            new_name='id',
        ),
    ]
