# Generated by Django 5.1.4 on 2025-03-04 13:34

from django.db import migrations, models

def migrate_card_number(apps, schema_editor):
    Customer = apps.get_model("store", "Customer")  # Get the model
    for customer in Customer.objects.iterator():
        #if not customer.id:  # Ensure ID is miss
        customer.card_number = customer.id
        customer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_card_number_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='card_number',
            field=models.CharField(default=0),
        ),
        migrations.RunPython(migrate_card_number)
    ]
