# Generated by Django 5.1.3 on 2025-01-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customerpurchase_order_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_deposits',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_purchases',
        ),
    ]
