# Generated by Django 5.1.4 on 2025-01-21 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_productrestock_cash_movement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogTraceback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('traceback', models.TextField()),
                ('line_no', models.IntegerField()),
                ('file_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='storelog',
            name='source_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='storelog',
            name='source_line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='storelog',
            name='traceback',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.logtraceback'),
        ),
    ]
