# Generated by Django 5.1.3 on 2025-01-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_customer_total_deposits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='total_deposits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='total_purchases',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
