# Generated by Django 5.1.4 on 2025-03-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_customer_card_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdeposit',
            name='comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
