# Generated by Django 5.1.4 on 2025-03-14 08:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_customerdeposit_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdeposit',
            name='flag',
            field=models.CharField(default='executed', max_length=100),
        ),
        migrations.AddField(
            model_name='customerdeposit',
            name='related_deposit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customerdeposit'),
        ),
    ]
