# Generated by Django 5.1.7 on 2025-03-30 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_customerdeposit_flag_customerdeposit_related_deposit'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeproduct',
            name='image_source',
            field=models.CharField(default='openfoodfacts', max_length=255),
        ),
    ]
